Created attribute_5 splash damage for attacking an enemy troop
Open-Source-Software-Development/Cardtorium pull request #76
Opened 2024-04-24 05:17 UTC by tealeaf2

2024-04-24 14:35 UTC, mayleenliu commented on Attributes/Troops/Logic/attribute_5.gd
> +    var splash_tiles = _get_surrounding(defender_pos, 1)
`_get_surrounding` is not declared in this code, so must change to `defender._get_surrounding` because it inherits from `troop.gd`

2024-04-24 14:41 UTC, mayleenliu requested changes

2024-04-24 14:41 UTC, mayleenliu commented on Attributes/Troops/Logic/attribute_5.gd
> +    var splash_tiles = _get_surrounding(defender_pos, 1)
`_get_surrounding` is not declared in this code, so must change to `defender._get_surrounding` because it inherits from `troop.gd`

2024-04-24 14:41 UTC, mayleenliu commented on Attributes/Troops/Logic/attribute_5.gd
> +        var unit_at_tile = game.board.units[tile.x][tile.y]
remove `game` because troop attribute already contains board as a variable

2024-04-24 14:41 UTC, mayleenliu commented on Attributes/Troops/Logic/attribute_5.gd
> +        apply_splash_damage(unit_at_tile)
Before applying splash damage, check if board.units[tile.x][tile.y] == null and continue if so.

2024-04-24 14:41 UTC, mayleenliu commented on Attributes/Troops/Logic/attribute_5.gd
> +        game.remove_unit(troop)
change `game` to `parent.game`

2024-04-24 14:41 UTC, mayleenliu commented on Attributes/Troops/Logic/attribute_5.gd
> +    var splash_damage = floor(base_stats.attack / 2.0)
Take a look at the damage calculations on lines 242, 224, 222 [here](https://github.com/Open-Source-Software-Development/Cardtorium/blob/main/Classes/troop.gd) and change what's here to match. Currently you're using the defending unit's attack, but you should also pass in the attacking unit and use it's attack.

2024-04-27 23:33 UTC, AnthonyBatt requested changes
@tealeaf2 great job on the other fixes, and , sorry for the confusion, but for this one the damage equation is still a bit off. The equation is rather complicated so I'll try to outline the four steps for you to implement:

1. `var atk_force  = attacker.attack * float(attacker.current_health)/float(attacker.max_health)`
2. `var def_force = defender.defense * float(defender.current_health)/float(defender.max_health)`
3. `var damage = floor((attack_force/(attack_force+def_force))*atk)`
4. `var splash_damage= damage / 2.0`

The variable names above might not be exactly what they are called in the code, but this is the general idea for the damage calculation.

2024-04-27 23:34 UTC, AnthonyBatt commented on Attributes/Troops/Logic/attribute_5.gd
> +    var splash_damage = floor(troop_attacker.attack / 2.0)
Sorry, I did not realize you couldn’t see the feedback, my bad

2024-04-29 14:59 UTC, AnthonyBatt approved these changes
@tealeaf2 thank you for all your work, and sorry again for the confusion. We really appreciated your contribution and I’ll go ahead and pull this in.

2024-04-29 15:00 UTC, merged